version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_USER=root
      - POSTGRES_DB=desafio_db